return {
  filetypes = {
    'css',
    'javascriptreact',
    'typescriptreact',

    -- 'aspnetcorerazor',
    -- 'astro',
    -- 'astro-markdown',
    -- 'blade',
    -- 'clojure',
    -- 'css',
    -- 'django-html',
    -- 'edge',
    -- 'eelixir',
    -- 'ejs',
    -- 'elixir',
    -- 'erb',
    -- 'eruby',
    -- 'gohtml',
    -- 'gohtmltmpl',
    -- 'haml',
    -- 'handlebars',
    -- 'hbs',
    -- 'heex',
    -- 'html',
    -- 'html-eex',
    -- 'htmlangular',
    -- 'htmldjango',
    -- 'jade',
    -- 'javascript',
    -- 'javascriptreact',
    -- 'leaf',
    -- 'less',
    -- 'liquid',
    -- 'markdown',
    -- 'mdx',
    -- 'mustache',
    -- 'njk',
    -- 'nunjucks',
    -- 'php',
    -- 'postcss',
    -- 'razor',
    -- 'reason',
    -- 'rescript',
    -- 'sass',
    -- 'scss',
    -- 'slim',
    -- 'stylus',
    -- 'sugarss',
    -- 'svelte',
    -- 'templ',
    -- 'twig',
    -- 'typescript',
    -- 'typescriptreact',
    -- 'vue',
  },
}
